# Generated by Django 4.2.2 on 2023-06-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='position',
            field=models.BooleanField(choices=[(False, 'No Position'), (True, 'Right Position')], default=False),
        ),
    ]
